docker: true
app:
  host: 0.0.0.0
  port: 18300
model:
  path: /model
  host: localhost
  port: 8001
  device_id: 0
  quantization:
  gpu_memory_utilization: 0.8
  max_model_len: 16384
  autostart: true
sampling:
  sample_size: 20
aggregator:
  base_url: http://news-aggregator:8000
  timeout_seconds: 15
